<a href="https://colab.research.google.com/github/Nabilahfzh17/Pembelajaran-Mesin/blob/main/UTS_1197050096_Nisairrizqy_Nabilah_Faizah.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# UTS Pembelajaran Mesin

Nisairrizqy Nabilah Faizah, 1197050096, Prak. dan Teori C

# Topik Mini Riset

Topik Mini Riset ini mengenai klasifikasi pasien yang positif dan negatif terpapar penyakit diabetes menggunakan algoritma KNN 

# Business Understanding 

### Latar Belakang Masalah
Diabetes merupakan penyakit yang terjadi akibat kadar glukosa di dalam darah terlalu tinggi. Kadar gula didalam darah dapat meningkat salah satunya disebabkan karena tubuh tidak dapat melepaskan atau menggunakan
insulin secara normal. Setiap individu memiliki kadar glukosa yang bervariasi, kadar glukosa ini akan meningkat setelah makan kemudian akan kembali normal dalam waktu dua jam. Pada umumnya kadar glukosa darah akan meningkat secara ringan pada usia muda, tetapi kadar glukosa ini akan mengalami peningkatan yang progresif pada usia lebih dari 50 tahun. Peningkatan kadar glukosa ini akan lebih terasa pada orang dengan gaya hidup pasif atau jarang beraktifitas. 
### Identifikasi Masalah
Dari latar belakang tersebut bisa kita ambil identifikasi masalah yang ada yaitu :
1. Bagaimana pengaruh gejala diabetes pada usia diatas 20 tahun
2. Apakah kadar glukosa sangat berpengaruh terhadap diabetes
### Metode
Data yang digunakan menggunakan dataset dari kaggle yang bersumber dari https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database dengan melakukan data mining pada dataset menggunakan algoritma KKN.
### Tujuan Teknis dan Kriteria Kesuksesan
Diharapkan dalam percobaan mini riset ini mampu melihat dan memprediksi apakah positif diabetes atau tidak berdasarkan gejala yang ditunjukan.
### Timeline Mini Riset
19-23 April 2022

# Data Understanding

### Kebutuhan Data
Data yang diperlukan dan digunakan yaitu data gejala penyakit diabetes
### Pengambilan Data
Data yang digunakan menggunakan dataset dari kaggle yang bersumber dari https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database
### Integrasi Data
Data diambil dari berbagai macam  gejala diabetes
### Telaah Data
data disini berisikan 9 dimensi dimana 700 Kumpulan Data Diabetes. berikut pembahasan mengenai 9 dimensi yang ada pada dataset:

1. Pregnancies
2. Glucose
3. BloodPressure
4. SkinThickness
5. Insulin
6. BMI
7. DiabetesPedigreeFunction
8. Age
9. Outcome
### Analisis Karakteristik Data
data berisikan data numerik 
### Validasi Data
700 data orang dengan berbagai gejala diabetes

In [17]:
#Import library yang akan gigunakan
import pandas as pd #Library panda untuk membaca file csv
from sklearn.model_selection import train_test_split #Train/test split adalah salah satu metode yang dapat digunakan untuk mengevaluasi performa model machine learning. Metode evaluasi model ini membagi dataset menjadi dua bagian yakni bagian yang digunakan untuk training data dan untuk testing data dengan proporsi tertentu.
from sklearn.preprocessing import StandardScaler #Library untuk melakukan tugas Standardisasi . Biasanya dataset berisi variabel yang berbeda dalam skala misal umur ada yang 48-60
scaler=StandardScaler() #Inisiasi fungsi scaler

In [22]:
#load data
url = 'https://raw.githubusercontent.com/Nabilahfzh17/Pembelajaran-Mesin/main/diabetes_data_upload.csv'
df = pd.read_csv(url, sep=',')

df.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

In [29]:
df.describe(include='all') #Menunjukkan rangkuman statistik seperti rata-rata, median, dll pada kolom.

Age Gender Polyuria Polydipsia sudden weight loss weakness  \
count   520.000000    520      520        520                520      520   
unique         NaN      2        2          2                  2        2   
top            NaN   Male       No         No                 No      Yes   
freq           NaN    328      262        287                303      305   
mean     48.028846    NaN      NaN        NaN                NaN      NaN   
std      12.151466    NaN      NaN        NaN                NaN      NaN   
min      16.000000    NaN      NaN        NaN                NaN      NaN   
25%      39.000000    NaN      NaN        NaN                NaN      NaN   
50%      47.500000    NaN      NaN        NaN                NaN      NaN   
75%      57.000000    NaN      NaN        NaN                NaN      NaN   
max      90.000000    NaN      NaN        NaN                NaN      NaN   

       Polyphagia Genital thrush visual blurring Itching Irritability  \
count         520            520             520     520          520   
unique          2              2               2       2            2   
top            No             No              No      No           No   
freq          283            404             287     267          394   
mean          NaN            NaN             NaN     NaN          NaN   
std           NaN            NaN             NaN     NaN          NaN   
min           NaN            NaN             NaN     NaN          NaN   
25%           NaN            NaN             NaN     NaN          NaN   
50%           NaN            NaN             NaN     NaN          NaN   
75%           NaN            NaN             NaN     NaN          NaN   
max           NaN            NaN             NaN     NaN          NaN   

       delayed healing partial paresis muscle stiffness Alopecia Obesity  \
count              520             520              520      520     520   
unique               2               2                2        2       2   
top                 No              No               No       No      No   
freq               281             296              325      341     432   
mean               NaN             NaN              NaN      NaN     NaN   
std                NaN             NaN              NaN      NaN     NaN   
min                NaN             NaN              NaN      NaN     NaN   
25%                NaN             NaN              NaN      NaN     NaN   
50%                NaN             NaN              NaN      NaN     NaN   
75%                NaN             NaN              NaN      NaN     NaN   
max                NaN             NaN              NaN      NaN     NaN   

           class  
count        520  
unique         2  
top     Positive  
freq         320  
mean         NaN  
std          NaN  
min          NaN  
25%          NaN  
50%          NaN  
75%          NaN  
max          NaN

In [30]:
#mendefinisikan fungsi untuk preprosessing data
def preprocessing(data):
    df= data.copy() #menyalin dataFrame yang disimpan di parameter data
    
    # Mengubah isi kolom gender yang semula female dan male menjadi 0 dan 1
    df['Gender'] = df ['Gender'].replace({'Female':0,'Male':1 })
    
    #Mengubah isi kolom selain Age, Gender, Class yang berisi 'No' dan 'Yes' menjadi 0 dan 1
    for column in df.columns.drop(['Age','Gender','class']):
        df[column]= df[column].replace({'No':0 , 'Yes': 1})
    
    #Melakukan Traning
    y=df["class"] #menyimpan kolom class ke variabel y
    X=df.drop("class", axis=1) #drop kolom class 
    
    #test_train_split membagi data menjadi dua bagian yaitu traning dan test
    X_train, X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,shuffle=True,random_state=1)
    
    #StandardScaler
    scaler.fit(X_train) #Hitung mean dan std yang akan digunakan untuk penskalaan nanti.
    X_train=pd.DataFrame(scaler.transform(X_train),index=X_train.index , columns=X_train.columns) #membuat dataframe menggunakan X_train
    X_test=pd.DataFrame(scaler.transform(X_test),index=X_test.index, columns=X_test.columns) #membuat dataframe menggunakan X_test
    
    return X_train,X_test,y_train,y_test #mereturn X_train,X_test, y_train, y_test ketika fungsi preprocessing di panggil

In [32]:
#memanggil fungsi preprocessing yang sudah di buat tadi dengan argumen data (variabel yang menyimpan dataset .csv)
X_train,X_test,y_train,y_test= preprocessing(df)

In [33]:
#menampilkan dataframe X_train
X_train

Age    Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
122 -0.658902  0.740902 -0.994521    1.129159           -0.846747  0.841974   
168 -0.913060  0.740902 -0.994521   -0.885615           -0.846747  0.841974   
23   0.018852  0.740902 -0.994521    1.129159            1.180990  0.841974   
13   1.120204  0.740902  1.005510    1.129159            1.180990  0.841974   
61  -1.082499 -1.349706  1.005510    1.129159            1.180990  0.841974   
..        ...       ...       ...         ...                 ...       ...   
129  0.018852  0.740902  1.005510    1.129159            1.180990  0.841974   
144  1.713239  0.740902  1.005510    1.129159           -0.846747 -1.187685   
72   1.459081 -1.349706 -0.994521   -0.885615           -0.846747 -1.187685   
235 -1.844973  0.740902 -0.994521   -0.885615           -0.846747 -1.187685   
37   1.289643  0.740902  1.005510    1.129159            1.180990  0.841974   

     Polyphagia  Genital thrush  visual blurring   Itching  Irritability  \
122    1.104315       -0.560428        -0.870893  1.044966      1.682730   
168   -0.905539       -0.560428        -0.870893 -0.956969     -0.594273   
23    -0.905539       -0.560428         1.148247  1.044966      1.682730   
13     1.104315        1.784351         1.148247  1.044966     -0.594273   
61     1.104315       -0.560428         1.148247  1.044966     -0.594273   
..          ...             ...              ...       ...           ...   
129   -0.905539       -0.560428        -0.870893  1.044966     -0.594273   
144    1.104315       -0.560428         1.148247  1.044966      1.682730   
72    -0.905539        1.784351        -0.870893 -0.956969     -0.594273   
235   -0.905539       -0.560428        -0.870893 -0.956969     -0.594273   
37     1.104315       -0.560428         1.148247 -0.956969     -0.594273   

     delayed healing  partial paresis  muscle stiffness  Alopecia   Obesity  
122         1.068259         1.148247          1.333651 -0.745356  2.165064  
168         1.068259        -0.870893         -0.749821  1.341641 -0.461880  
23          1.068259        -0.870893         -0.749821 -0.745356 -0.461880  
13         -0.936103        -0.870893         -0.749821  1.341641  2.165064  
61          1.068259         1.148247          1.333651 -0.745356 -0.461880  
..               ...              ...               ...       ...       ...  
129        -0.936103         1.148247         -0.749821  1.341641 -0.461880  
144        -0.936103         1.148247         -0.749821 -0.745356 -0.461880  
72         -0.936103        -0.870893         -0.749821 -0.745356 -0.461880  
235        -0.936103        -0.870893         -0.749821 -0.745356 -0.461880  
37         -0.936103        -0.870893          1.333651  1.341641  2.165064  

[364 rows x 16 columns]

In [34]:
#import library KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2) #settingan default knn
knn.fit(X_train, y_train) #setelah membuat data train dan test, maka masukkan data training pada fungsi klasifikasi KNN

KNeighborsClassifier()

In [35]:
y_pred = knn.predict(X_test) #melakukan prediksi ke data test 
y_pred

array(['Negative', 'Negative', 'Negative', 'Negative', 'Positive',
       'Positive', 'Negative', 'Positive', 'Negative', 'Positive',
       'Negative', 'Negative', 'Positive', 'Positive', 'Negative',
       'Positive', 'Negative', 'Negative', 'Positive', 'Positive',
       'Positive', 'Negative', 'Positive', 'Negative', 'Positive',
       'Negative', 'Positive', 'Positive', 'Negative', 'Positive',
       'Positive', 'Positive', 'Negative', 'Positive', 'Negative',
       'Positive', 'Positive', 'Negative', 'Negative', 'Positive',
       'Negative', 'Negative', 'Negative', 'Positive', 'Positive',
       'Positive', 'Positive', 'Negative', 'Negative', 'Positive',
       'Negative', 'Positive', 'Positive', 'Positive', 'Positive',
       'Positive', 'Negative', 'Negative', 'Negative', 'Negative',
       'Negative', 'Negative', 'Positive', 'Negative', 'Positive',
       'Negative', 'Negative', 'Positive', 'Positive', 'Positive',
       'Negative', 'Positive', 'Negative', 'Positive', 'Negati

In [36]:
#menghitung matrix confusion dari test dengan prediksi klasifikasi knn
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[54,  4],
       [11, 87]])

Dari model knn yang kita buat berdasarkan matrik confusion kita mendapat 
True Positif = 54, False Positif = 4, True Negatif = 87, False Negatif = 11

In [37]:
#menghitung akurasi dari model yang dibuat
from sklearn.metrics import accuracy_score
round(accuracy_score(y_pred,y_test)*100,2)

90.38

Akurasi model knn yang dibuat sebesar 90.38 persen

In [38]:
#melakukan prediksi menggunakan data baru (No = 0 Yes = 1) dan gender (Male = 1 Female= 0)
#Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity
print(knn.predict(scaler.transform([[42,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1]])))

['Negative']


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


In [39]:
#import library SVM
from sklearn import svm

sv = svm.SVC(kernel='linear')

sv.fit(X_train, y_train) #masukkan data training pada fungsi klasifikasi SVM

Y_pred_svm = sv.predict(X_test) #melakukan prediksi pada data test

Y_pred_svm

array(['Negative', 'Negative', 'Negative', 'Negative', 'Positive',
       'Positive', 'Positive', 'Negative', 'Negative', 'Positive',
       'Negative', 'Negative', 'Positive', 'Positive', 'Negative',
       'Positive', 'Negative', 'Negative', 'Positive', 'Positive',
       'Positive', 'Negative', 'Positive', 'Negative', 'Positive',
       'Negative', 'Positive', 'Positive', 'Negative', 'Positive',
       'Negative', 'Positive', 'Negative', 'Positive', 'Negative',
       'Positive', 'Positive', 'Negative', 'Negative', 'Positive',
       'Negative', 'Negative', 'Positive', 'Positive', 'Positive',
       'Positive', 'Positive', 'Negative', 'Positive', 'Positive',
       'Negative', 'Positive', 'Positive', 'Positive', 'Positive',
       'Positive', 'Negative', 'Negative', 'Negative', 'Negative',
       'Positive', 'Negative', 'Positive', 'Negative', 'Positive',
       'Negative', 'Positive', 'Positive', 'Positive', 'Positive',
       'Positive', 'Negative', 'Negative', 'Positive', 'Negati

In [40]:
#menghitung matrix confusion dari test dengan prediksi klasifikasi svm
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, Y_pred_svm)
cm

array([[53,  5],
       [ 8, 90]])

Dari model svm yang kita buat berdasarkan matrik confusion kita mendapat True Positif = 53, False Positif = 5, True Negatif = 90, False Negatif = 8

In [41]:
score_svm = round(accuracy_score(Y_pred_svm,y_test)*100,2) #menghitung akurasi klasifikasi SVM

score_svm

91.67

Skor akurasi klasifikasi SVM mencapai 91.67 persen